# Kubernetes implements HPA as a control loop: every ~15 seconds it fetches pod metrics

apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata: { name: shopping-hpa }
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: shopping
  minReplicas: 1
  maxReplicas: 4
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 50