apiVersion: v1
kind: Service
metadata:
  name: kafka
  namespace: kafka
spec:
  type: NodePort
  selector:
    app.kubernetes.io/name: kafka
    app.kubernetes.io/instance: kafka
  ports:
    - port: 9092
      targetPort: 9092
      nodePort: 30092        # any port in 30000-32767