replicaCount: 1

auth:
  clientProtocol: plaintext               # dev only, no TLS/SASL

listeners:
  client:
    protocol: PLAINTEXT
    containerPort: 9092

service:
  type: ClusterIP
  ports:
    client: 9092

zookeeper:
  enabled: true

# --- Broker-level overrides ----------------------------------------------
configurationOverrides:
  "num.partitions": 4                     
  "auto.create.topics.enable": "false"    

# --- Topic provisioning job ----------------------------------------------
provisioning:
  enabled: true                           
  numPartitions: 1                        
  replicationFactor: 1                    
  topics:
    - name: orders
      partitions: 4                      
      replicationFactor: 1
      config:
        cleanup.policy: compact
    - name: payments
      partitions: 4                       
      replicationFactor: 1
      config:
        retention.ms: "604800000"         
