apiVersion: apps/v1
kind: Deployment
metadata: { name: notification }
spec:
  replicas: 1
  selector: { matchLabels: { app: notification } }
  template:
    metadata: { labels: { app: notification } }
    spec:
      containers:
      - name: notification
        image: codingmao/ds_ecommerce_notification:1.0
        env:                                
        - name: KAFKA_BROKER
          value: kafka.kafka.svc.cluster.local:9092
        ports: [{ containerPort: 3000 }]
---
apiVersion: v1
kind: Service
metadata: { name: notification-svc }
spec:
  type: NodePort
  selector: { app: notification }
  ports:
  - port: 80            # 叢集內部 port
    targetPort: 3000    # 容器 port
    nodePort: 30083     # 主機對外 port（任選 30000-32767）
