apiVersion: apps/v1
kind: Deployment
metadata: { name: payment }
spec:
  replicas: 1
  selector: { matchLabels: { app: payment } }
  template:
    metadata: { labels: { app: payment } }
    spec:
      containers:
      - name: payment
        image: codingmao/ds_ecommerce_payment:1.0
        env:                                
        - name: KAFKA_BROKER
          value: kafka.kafka.svc.cluster.local:9092
        ports: [{ containerPort: 3000 }]
---
apiVersion: v1
kind: Service
metadata: { name: payment-svc }
spec:
  type: NodePort
  selector: { app: payment }
  ports:
  - port: 80            # 叢集內部 port
    targetPort: 4000    # 容器 port
    nodePort: 30082     # 主機對外 port（任選 30000-32767）
