apiVersion: apps/v1
kind: Deployment
metadata: { name: shopping }
spec:
  replicas: 1
  selector: { matchLabels: { app: shopping } }
  template:
    metadata: { labels: { app: shopping } }
    spec:
      containers:
      - name: shopping
        image: codingmao/ds_ecommerce_shopping:1.0
        env:                                
        - name: KAFKA_BROKER
          value: kafka.kafka.svc.cluster.local:9092
        ports: [{ containerPort: 3000 }]
        resources:
          requests:
            cpu: 100m       # baseline for HPA calculations
            memory: 128Mi   # optional, improves scheduling
          limits:
            cpu: 200m       # optional cap
            memory: 256Mi   # optional cap
---
apiVersion: v1
kind: Service
metadata: { name: shopping-svc }
spec:
  type: NodePort
  selector: { app: shopping }
  ports:
  - port: 80            # 叢集內部 port
    targetPort: 3000    # 容器 port
    nodePort: 30081     # 主機對外 port（任選 30000-32767）
